### ISSUE TITLE
Find out difference between separate devtools.

### ISSUE THREAD

**Issue by AriaFallah** [AriaFallah/WebpackTutorial#2]
What's the difference between all the different source maps?

For example: `cheap-eval-source-map` vs `source-map`

**Comment by garmjs** [comment]
https://webpack.github.io/docs/configuration.html#devtool

SourceMaps are a bit slow, because every line in source need to tracked and the resulting SourceMaps are pretty big. They are only updated when a chunk has changed, so smaller chunk may result in fast rebuilds.

The eval devtool is much faster, because it only need to stringify the source and nothing need to be tracked.

the eval tool is enough (if you develop in a non-js language, i.e. coffeescript, you may need SourceMaps). 
Maybe [#169](https://github.com/webpack/webpack/issues/169) can provide better performance for SourceMaps.

The rebuilds with eval-source-map seem to be as fast as with eval.

**Comment by AriaFallah** [comment]
@ArmendGashi Something I haven't done that I would also like to do is show the difference between the outputted source maps. However, I don't necessarily know how to demonstrate that since the sourcemaps are minified and all.

**Comment by garmjs** [comment]
You can test the performance of several `devtool` [options](https://webpack.github.io/docs/configuration.html#devtool) and maybe show the result.

**Comment by AriaFallah** [comment]
.
