### ISSUE TITLE
Please add more preset and plugin examples

### ISSUE THREAD

**Issue by kristianmandrup** [AriaFallah/WebpackTutorial#40]
I have seen there are now 2017 and including -minimal and -latest presets available. 
The minimal uses feature detection to only transpile for features not supported for the Node.js version being used!

Also, what about plugins for advanced features such as (legacy) decorators and async/await?

Good job! Looking forward to more tutorials and general tutorial improvements!
How about code coverage!?

**Comment by AriaFallah** [comment]
Hey I'm gonna address both your tickets here. I'm currently too busy to update the tutorial, and by no means do I intend for it to be comprehensive. The focus is on simplicity instead of abstractions or extra plugins/presets.

In the late future, I will definitely release a "second edition" that updates the outdated information, but nothing more than improvements to clarity as the original reason I created the tutorial was for it to be focused and small. I feel like adding more content or talking about DRYness is unnecessary complication that shouldn't go into the main tutorial, but maybe an "extras" type thing at the end.

I'll definitely take your suggestions into consideration, but for the time being...I just am too busy for this tutorial to be a priority. Sorry 😕 .
